// WGC_Frontend/src/app/software-partners/page.tsx
import Link from "next/link";
import { ArrowRight, ChevronDown, CheckCircle2, ShieldCheck, Zap, Globe, BarChart3, Settings } from "lucide-react";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import CTASection from "@/components/ui/CTASection";
import ScrollFade from "@/components/ui/ScrollFade";

const FEATURES = [
  {
    title: "White-Labeled Infrastructure",
    description: "Launch your own payment platform in days. WGC stays hidden while providing the institutional rails your partners expect.",
    icon: Settings,
  },
  {
    title: "Flat-Rate ACH",
    description: "Honoring the donor's intent with 25¢ flat-rate ACH transfers. No percentage-based gouging on large tithes.",
    icon: Zap,
  },
  {
    title: "Recurring Giving Engine",
    description: "Robust, automated recurring engine with native pause/resume and flexible scheduling built-in.",
    icon: Globe,
  },
  {
    title: "PCI Level 1 Compliance",
    description: "The highest level of security. We handle the compliance burden so you can focus on building your software.",
    icon: ShieldCheck,
  },
  {
    title: "Merchant Orchestration",
    description: "Onboard merchants, manage settlements, and handle payouts across your entire network from a single API.",
    icon: BarChart3,
  },
  {
    title: "Mission Alignment",
    description: "We don't serve retail. We don't serve the world. We serve the people who serve the Kingdom.",
    icon: CheckCircle2,
  },
];

export default function SoftwarePartnersPage() {
  return (
    <>
      <Header />
      <main className="flex-grow">
        {/* DARK HERO */}
        <section className="relative bg-wgc-off pt-32 pb-24 overflow-hidden border-b border-wgc-navy-800">
          <div className="absolute inset-0 opacity-[0.04]">
            <svg className="w-full h-full" fill="none">
              <pattern id="partners-hero-grid" x="0" y="0" width="28" height="28" patternUnits="userSpaceOnUse">
                <path d="M 28 0 L 0 0 0 28" fill="none" stroke="white" strokeWidth="0.5" />
              </pattern>
              <rect width="100%" height="100%" fill="url(#partners-hero-grid)" />
            </svg>
          </div>
          <div className="absolute top-1/2 right-0 -translate-y-1/2 w-96 h-96 rounded-full blur-3xl opacity-10 pointer-events-none" style={{ background: "radial-gradient(circle, #eab308 0%, transparent 70%)" }}></div>

          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
            <div className="lg:grid lg:grid-cols-2 lg:gap-16 items-center">
              <ScrollFade>
                <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full mb-8 border border-wgc-gold-500/30 bg-wgc-gold-500/10">
                  <div className="w-1.5 h-1.5 rounded-full bg-wgc-gold-500"></div>
                  <span className="text-[10px] font-bold uppercase tracking-[0.3em] text-wgc-gold-500/90">Software Partnership</span>
                </div>
                <h1 className="text-5xl sm:text-6xl font-bold tracking-tight leading-[1.05] mb-6 text-slate-50">
                  Embedded payments for <br /><span className="text-wgc-gold-500">Ministry SaaS.</span>
                </h1>
                <p className="text-xl font-medium leading-relaxed mb-10 text-wgc-navy-500 tracking-tight">
                  Integrate donations, recurring giving, ACH payments, and payouts directly into your platform — fully white-labeled.
                </p>
                <div className="flex flex-col sm:flex-row gap-4">
                  <Link href="/contact" className="bg-wgc-gold-500 text-wgc-navy-900 inline-flex items-center justify-center px-8 py-4 text-sm font-bold rounded-full shadow-xl transform transition-all hover:scale-105 uppercase tracking-wider">
                    Apply for Partnership
                  </Link>
                  <Link href="/developers" className="inline-flex items-center justify-center px-8 py-4 text-sm font-bold rounded-full transition-all uppercase tracking-wider border border-slate-700 text-wgc-navy-500 hover:text-wgc-navy-900 hover:border-slate-500">
                    Review API Docs
                  </Link>
                </div>
              </ScrollFade>

              {/* Right Side Visual Card */}
              <ScrollFade delay={200}>
                <div className="mt-16 lg:mt-0 relative group">
                  <div className="relative rounded-[3rem] overflow-hidden shadow-[0_20px_50px_rgba(0,0,0,0.3)] border border-white/10 aspect-[4/5] lg:aspect-auto lg:h-[600px]">
                    <img 
                      src="/images/partners.png" 
                      alt="Partner Collaboration"
                      className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-105 brightness-[1.02]"
                    />
                    
                    {/* Bottom: Solid Quote Bar */}
                    <div className="absolute bottom-0 left-0 right-0 bg-slate-950/90 backdrop-blur-md p-10 border-t border-white/10">
                      <div className="relative z-10 flex items-center gap-3 mb-6">
                        <div className="w-10 h-px bg-wgc-gold-500"></div>
                        <span className="text-[10px] font-bold uppercase tracking-[0.3em] text-wgc-gold-500/70">Our Core Mandate</span>
                      </div>

                      <blockquote className="relative z-10">
                        <p className="text-xl sm:text-2xl font-bold leading-snug italic mb-4 text-slate-50 tracking-tight">
                          &quot;Go and make disciples of all nations.&quot;
                        </p>
                        <footer className="flex items-center gap-3">
                          <span className="font-bold text-[11px] uppercase tracking-widest text-wgc-gold-500/60 font-mono">Matthew 28:19</span>
                        </footer>
                      </blockquote>
                    </div>
                  </div>
                </div>
              </ScrollFade>
            </div>
          </div>
        </section>

        {/* PROOF BAND */}
        <div className="bg-wgc-off border-b border-wgc-navy-800 py-8 text-center px-4 overflow-hidden relative">
          <div className="max-w-4xl mx-auto flex flex-wrap justify-center gap-6 sm:gap-12 text-wgc-navy-900 font-bold uppercase tracking-widest text-[11px]">
            <div className="flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-wgc-gold-500"></div> Built for Church CRMs</div>
            <div className="flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-wgc-gold-500"></div> Recurring Giving Engine</div>
            <div className="flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-wgc-gold-500"></div> ACH + Card Payments</div>
            <div className="flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-wgc-gold-500"></div> White-label Experience</div>
          </div>
        </div>

        {/* PLATFORMS */}
        <section className="py-24 bg-wgc-off border-b border-wgc-navy-100/30">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <ScrollFade>
              <div className="text-center mb-16">
                <div className="inline-flex items-center px-4 py-1.5 rounded-full bg-wgc-navy-50 text-wgc-navy-600 text-[10px] font-bold tracking-[0.2em] uppercase mb-6 border border-wgc-navy-100 font-mono">Partnership focus</div>
                <h2 className="text-4xl font-bold text-wgc-navy-900 tracking-tight">Built for the platforms you trust</h2>
                <p className="text-lg text-wgc-navy-500 font-medium max-w-2xl mx-auto mt-4 tracking-tight opacity-90">Providing institutional-grade payment rails beneath the software that ministries use every day.</p>
              </div>
            </ScrollFade>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {['Church Management (ChMS)', 'Donation Platforms', 'Nonprofit CRMs', 'Faith-based SaaS'].map((platform, i) => (
                <ScrollFade key={platform} delay={i * 100}>
                  <div className="p-8 rounded-2xl bg-white border border-wgc-navy-100 shadow-sm hover:shadow-md transition-all group hover:-translate-y-1">
                     <div className="text-lg font-bold text-wgc-navy-900 group-hover:text-wgc-gold-600 transition-colors">{platform}</div>
                     <div className="w-8 h-1 bg-wgc-gold-500 mt-4 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"></div>
                  </div>
                </ScrollFade>
              ))}
            </div>
          </div>
        </section>

        {/* PARTNER FLOW */}
        <section className="py-24 bg-white border-b border-wgc-navy-100/30">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <h2 className="text-3xl font-bold text-wgc-navy-900 sm:text-4xl tracking-tight mb-16">The Partner Flow</h2>
            
            <div className="flex flex-col lg:flex-row items-center justify-center lg:items-stretch gap-8 relative">
              {/* Connector Line (Desktop) */}
              <div className="hidden lg:block absolute top-[60%] left-[20%] right-[20%] h-px bg-gradient-to-r from-transparent via-wgc-gold-500/30 to-transparent z-0"></div>

              {/* Step 1 */}
              <ScrollFade className="w-full lg:flex-1 relative z-10">
                <div className="h-full p-12 rounded-[2.5rem] border border-wgc-navy-100 bg-wgc-off shadow-sm hover:bg-white hover:shadow-xl transition-all duration-500 group">
                  <div className="text-[10px] font-bold text-wgc-navy-400 uppercase tracking-[0.3em] mb-8 font-mono group-hover:text-wgc-gold-600">Merchant Interface</div>
                  <div className="text-3xl font-bold text-wgc-navy-900 tracking-tighter leading-none">Your <br />Software</div>
                </div>
              </ScrollFade>
              
              <div className="flex items-center justify-center py-4 lg:py-0 relative z-10">
                <div className="w-12 h-12 rounded-full bg-wgc-gold-50 border border-wgc-gold-200 flex items-center justify-center shadow-sm">
                  <ArrowRight className="w-5 h-5 text-wgc-gold-600 hidden lg:block" />
                  <ChevronDown className="w-5 h-5 text-wgc-gold-600 lg:hidden" />
                </div>
              </div>
              
              {/* Step 2 (The Hub) */}
              <ScrollFade delay={150} className="w-full lg:flex-1 relative z-10">
                <div className="h-full p-12 rounded-[2.5rem] border border-wgc-gold-500/30 bg-white shadow-2xl relative overflow-hidden group hover:scale-[1.02] transition-transform duration-500">
                  <div className="absolute inset-0 bg-gradient-to-br from-wgc-gold-500/5 to-transparent opacity-50"></div>
                  <div className="absolute -bottom-10 -right-10 opacity-10 pointer-events-none select-none text-[12rem] font-bold text-wgc-gold-500 leading-none transition-transform group-hover:scale-110">✝</div>
                  
                  <div className="relative z-10 text-[10px] font-bold text-wgc-gold-500 uppercase tracking-[0.3em] mb-8 font-mono">Core Infrastructure</div>
                  <div className="relative z-10 text-3xl font-bold text-wgc-navy-900 tracking-tighter leading-none">WGC Payments <br /><span className="text-wgc-gold-500">Gateway API</span></div>
                </div>
              </ScrollFade>
              
              <div className="flex items-center justify-center py-4 lg:py-0 relative z-10">
                <div className="w-12 h-12 rounded-full bg-wgc-gold-50 border border-wgc-gold-200 flex items-center justify-center shadow-sm">
                  <ArrowRight className="w-5 h-5 text-wgc-gold-600 hidden lg:block" />
                  <ChevronDown className="w-5 h-5 text-wgc-gold-600 lg:hidden" />
                </div>
              </div>
              
              {/* Step 3 */}
              <ScrollFade delay={300} className="w-full lg:flex-1 relative z-10">
                <div className="h-full p-12 rounded-[2.5rem] border border-wgc-navy-100 bg-wgc-off shadow-sm hover:bg-white hover:shadow-xl transition-all duration-500 group">
                  <div className="text-[10px] font-bold text-wgc-navy-400 uppercase tracking-[0.3em] mb-8 font-mono group-hover:text-wgc-gold-600">Final Recipients</div>
                  <div className="text-3xl font-bold text-wgc-navy-900 tracking-tighter leading-none">Institutional <br />Merchant</div>
                </div>
              </ScrollFade>
            </div>
          </div>
        </section>

        {/* ADVANTAGE */}
        <section className="py-24 lg:py-32 bg-wgc-off border-t border-wgc-navy-100/10">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <ScrollFade>
              <div className="text-center mb-20">
                <h2 className="text-4xl font-bold text-wgc-navy-900 mb-6 tracking-tight">The Partner Advantage</h2>
                <p className="mt-4 max-w-2xl text-lg text-wgc-navy-500 font-medium mx-auto tracking-tight opacity-90">Everything you need to launch a world-class payment platform, without the burden.</p>
              </div>
            </ScrollFade>
            
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-10">
              {FEATURES.map((feature, i) => (
                <ScrollFade key={feature.title} delay={i * 80}>
                  <div className="bg-white p-10 rounded-3xl border border-wgc-navy-100 shadow-sm hover:shadow-lg transition-all transform hover:-translate-y-1 h-full text-left">
                    <div className="w-12 h-12 bg-wgc-navy-50 rounded-2xl flex items-center justify-center text-wgc-gold-500 mb-8 border border-wgc-navy-100">
                      <feature.icon className="w-6 h-6" />
                    </div>
                    <h3 className="text-xl font-bold text-wgc-navy-900 mb-4 tracking-tight">{feature.title}</h3>
                    <p className="text-wgc-navy-500 font-medium leading-relaxed tracking-tight opacity-80">{feature.description}</p>
                  </div>
                </ScrollFade>
              ))}
            </div>
          </div>
        </section>

        {/* QUOTE */}
        <section className="py-24 bg-white border-y border-wgc-navy-50">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <ScrollFade>
              <div className="w-12 h-1.5 metallic-gold mx-auto mb-10 rounded-full"></div>
              <h2 className="text-4xl font-bold text-wgc-navy-900 mb-10 tracking-tight leading-tight">Embedded Payments for Church and Nonprofit Software</h2>
              <div className="max-w-3xl mx-auto text-wgc-navy-500 space-y-8">
                <p className="text-2xl italic font-bold text-wgc-navy-900 leading-snug">
                  &quot;We exist to make software companies that serve churches more successful. We&apos;re not building a direct-to-church product. We&apos;re your silent infrastructure.&quot;
                </p>
                <p className="text-lg font-medium leading-relaxed tracking-tight opacity-90">
                  WGC is the institutional infrastructure under your software — aligned with your growth and your mission. By using a transferable vault and providing flat-rate ACH, we ensure that your platform scales efficiently while honoring the donors&apos; generosity.
                </p>
              </div>
            </ScrollFade>
          </div>
        </section>

        {/* COMPARISON */}
        <section className="py-24 bg-wgc-off">
          <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
            <ScrollFade>
              <div className="text-center mb-16">
                <h2 className="text-3xl font-bold text-wgc-navy-900 tracking-tight mb-4">Purpose-Built Infrastructure</h2>
                <p className="text-lg text-wgc-navy-500 font-medium max-w-2xl mx-auto tracking-tight opacity-90">Why software platforms choose WGC over generic payment rails.</p>
              </div>
            </ScrollFade>
            
            <ScrollFade>
              <div className="overflow-hidden rounded-3xl bg-white shadow-xl border border-wgc-navy-100">
                <table className="w-full text-left">
                  <thead className="bg-wgc-off text-wgc-navy-900">
                    <tr>
                      <th className="py-6 px-10 text-[10px] font-bold uppercase tracking-widest">Platform Feature</th>
                      <th className="py-6 px-10 text-[10px] font-bold uppercase tracking-widest text-center text-wgc-gold-500">WGC Payments</th>
                      <th className="py-6 px-10 text-[10px] font-bold tracking-widest text-center text-wgc-navy-950/40 uppercase">Horizontal Rails</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-wgc-navy-50">
                    {[
                      { f: 'Built for Ministries', w: 'Native alignment', s: 'Broad Retail' },
                      { f: 'ACH Optimization', w: '25¢ Flat-rate', s: 'Margin heavy' },
                      { f: 'Experience', w: 'Fully White-labeled', s: 'Redirected' }
                    ].map((row) => (
                      <tr key={row.f}>
                        <td className="py-6 px-10 font-bold text-wgc-navy-900 tracking-tight">{row.f}</td>
                        <td className="py-6 px-10 text-center font-bold text-wgc-navy-700 bg-wgc-gold-500/5 tracking-tight">{row.w}</td>
                        <td className="py-6 px-10 text-center text-wgc-navy-950 font-medium tracking-tight">{row.s}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </ScrollFade>
          </div>
        </section>

        {/* CTA */}
        <CTASection
          headline="Ready to power Kingdom giving?"
          subheadline="Contact our team to review your software roadmap and request sandbox access."
          ctaText="Contact us"
          ctaLink="/contact"
        />
      </main>
      <Footer />
    </>
  );
}

// WGC Frontend/src/app/pages/software-partners/software-partners.component.ts
import { Component, Inject, OnInit } from '@angular/core';
import { CommonModule, DOCUMENT } from '@angular/common';
import { RouterLink } from '@angular/router';
import { FeatureCardComponent } from '../../components/feature-card/feature-card.component';
import { CtaSectionComponent } from '../../components/cta-section/cta-section.component';
import { LucideAngularModule, Palette, Repeat, Landmark, UserPlus, FileSpreadsheet, Webhook, ChevronDown, ChevronUp, ArrowRight } from 'lucide-angular';

import { ScrollFadeDirective } from '../../directives/scroll-fade.directive';

@Component({
  selector: 'app-software-partners',
  standalone: true,
  imports: [CommonModule, RouterLink, FeatureCardComponent, CtaSectionComponent, LucideAngularModule, ScrollFadeDirective],
  templateUrl: './software-partners.component.html',
  styleUrl: './software-partners.component.css'
})
export class SoftwarePartnersComponent implements OnInit {
  readonly ChevronDown = ChevronDown;
  readonly ChevronUp = ChevronUp;
  readonly ArrowRight = ArrowRight;
  
  constructor(@Inject(DOCUMENT) private document: Document) {}

  faqs = [
    { q: "How does WGC compare to Stripe for nonprofits?", a: "WGC was built specifically for the church and nonprofit software ecosystem. While Stripe focuses on broad e-commerce, we offer flat-rate ACH natively, a transferable donor vault, and robust church-first integration features not found in generic platforms." },
    { q: "Can I white-label church payment processing?", a: "Yes. WGC is built embed-first. Software platforms can launch payments fully embedded within their ChMS using our pre-built modules or our strictly typed REST API, ensuring the church only ever sees your brand." },
    { q: "What are WGC's fees for 501(c)(3) organizations?", a: "We believe generously should flow freely. WGC offers transparent, flat-rate pricing well below industry standards, including a 0.5% flat-rate ACH capped at $5." },
    { q: "How fast are payouts to churches?", a: "Donations are processed efficiently and payouts are typically routed for next-business-day settlement directly to the church’s depository account." },
    { q: "Is WGC PCI compliant?", a: "Absolutely. WGC operates at PCI-DSS Level 1. Credit card data is rigorously vaulted and never directly touches your software application server, eliminating your PCI liability." },
    { q: "How do I migrate from Tithe.ly or Pushpay?", a: "Our dedicated engineering team guides the data migration processes to safely transition vaulted payment methods over to your new platform securely." }
  ];

  openFaq: string | null = null;
  toggleFaq(question: string) {
    this.openFaq = this.openFaq === question ? null : question;
  }

  ngOnInit() {
    this.injectFaqSchema();
  }

  private injectFaqSchema() {
    const existingScript = this.document.head.querySelector('#faq-schema');
    if (existingScript) return;

    const schema = {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      "mainEntity": this.faqs.map(f => ({
        "@type": "Question",
        "name": f.q,
        "acceptedAnswer": {
          "@type": "Answer",
          "text": f.a
        }
      }))
    };

    const script = this.document.createElement('script');
    script.id = 'faq-schema';
    script.type = 'application/ld+json';
    script.text = JSON.stringify(schema);
    this.document.head.appendChild(script);
  }

  features = [
    { icon: Palette, title: 'White-label payments', description: 'Fully embed payments into your platform. Your brand, your experience, our infrastructure.' },
    { icon: Repeat, title: 'Recurring giving system', description: 'A robust engine specifically designed for church pledges, tithes, and automated schedules.' },
    { icon: Landmark, title: 'ACH optimization', description: 'Flat-rate ACH processing passed at cost to ensure maximum funds reach the ministry.' },
    { icon: UserPlus, title: 'Merchant onboarding', description: 'Automated, white-labeled KYC and underwriting tailored for 501(c)(3) organizations.' },
    { icon: FileSpreadsheet, title: 'Payout & reporting system', description: 'Next-day settlements natively synced to your CRM for seamless reconciliation.' },
    { icon: Webhook, title: 'Webhooks and APIs', description: 'Developer-first SDK with strict typings, robust sandboxing, and real-time event streaming.' }
  ];

  codeSnippet = `// Process a donation through WGC
const donation = await wgc.donations.create({
  merchantId: 'mch_firstbaptist',
  amount: 10000,  // $100.00
  fund: 'general',
  paymentToken: token,
  donor: { email: 'donor@example.com' }
});`;
}

<!-- ==================== DARK HERO ==================== -->
<section class="relative bg-wgc-navy-900 pt-32 pb-24 overflow-hidden border-b border-wgc-navy-800">
  <div class="absolute inset-0 opacity-[0.04]">
    <svg class="w-full h-full" fill="none">
      <pattern id="partners-hero-grid" x="0" y="0" width="28" height="28" patternUnits="userSpaceOnUse">
        <path d="M 28 0 L 0 0 0 28" fill="none" stroke="white" stroke-width="0.5"/>
      </pattern>
      <rect width="100%" height="100%" fill="url(#partners-hero-grid)"/>
    </svg>
  </div>
  <div class="absolute top-1/2 right-0 -translate-y-1/2 w-96 h-96 rounded-full blur-3xl opacity-10 pointer-events-none" style="background: radial-gradient(circle, #eab308 0%, transparent 70%);"></div>

  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
    <div class="lg:grid lg:grid-cols-2 lg:gap-16 items-center">
      <div>
        <div class="inline-flex items-center gap-2 px-4 py-1.5 rounded-full mb-8 border" style="background: rgba(234,179,8,0.1); border-color: rgba(234,179,8,0.3);">
          <div class="w-1.5 h-1.5 rounded-full bg-wgc-gold-500"></div>
          <span class="text-[10px] font-black uppercase tracking-[0.3em]" style="color: rgba(234,179,8,0.9);">Software Partnership</span>
        </div>
        <h1 class="text-5xl sm:text-6xl font-black tracking-tight leading-[1.05] mb-6" style="color: #f8fafc;">
          Embedded payments for <br><span style="color: #eab308;">Ministry SaaS.</span>
        </h1>
        <p class="text-xl font-medium leading-relaxed mb-10" style="color: #94a3b8;">
          Integrate donations, recurring giving, ACH payments, and payouts directly into your platform — fully white-labeled.
        </p>
        <div class="flex flex-col sm:flex-row gap-4">
          <a routerLink="/contact" class="metallic-gold inline-flex items-center justify-center px-8 py-4 text-sm font-black rounded-full shadow-xl transform transition-all hover:scale-105 uppercase tracking-wider text-wgc-navy-900">
            Apply for Partnership
          </a>
          <a routerLink="/developers" class="inline-flex items-center justify-center px-8 py-4 text-sm font-bold rounded-full transition-all uppercase tracking-wider border" style="color: #94a3b8; border-color: rgba(148,163,184,0.3);">
            Review API Docs
          </a>
        </div>
      </div>

      <!-- Right Side Visual Card -->
      <div class="mt-16 lg:mt-0">
        <div class="relative rounded-3xl p-10 overflow-hidden shadow-2xl" 
             style="background: linear-gradient(145deg, #020617 0%, #0f172a 60%, #1a2540 100%); border: 1px solid rgba(234,179,8,0.2);">
          <div class="absolute -bottom-6 -right-6 opacity-[0.05] pointer-events-none select-none" style="font-size: 14rem; color: #eab308; font-weight: 900; line-height: 1;">✝</div>
          
          <div class="relative z-10 flex items-center gap-3 mb-8">
            <div class="w-10 h-1 rounded-full" style="background: linear-gradient(90deg, #eab308, #ca8a04);"></div>
            <span class="text-[10px] font-black uppercase tracking-[0.3em]" style="color: rgba(234,179,8,0.7);">Our Core Mandate</span>
          </div>

          <blockquote class="relative z-10 mb-8">
            <p class="text-2xl font-bold leading-snug italic mb-5" style="color: #f8fafc;">
              "Go and make disciples of all nations."
            </p>
            <footer class="flex items-center gap-3">
              <div class="w-6 h-px" style="background: rgba(234,179,8,0.5);"></div>
              <span class="font-black text-[11px] uppercase tracking-widest" style="color: #eab308;">Matthew 28:19</span>
            </footer>
          </blockquote>

          <div class="relative z-10 border-t my-6" style="border-color: rgba(234,179,8,0.1);"></div>

          <div class="relative z-10 space-y-4 mb-8">
            @for (item of ['White-labeled donations in days', 'Flat-rate ACH at 25¢', 'Automated recurring engine', 'PCI Level 1 Compliance']; track item) {
              <div class="flex items-center gap-4">
                <div class="w-5 h-5 rounded-full flex-shrink-0 flex items-center justify-center" style="background: rgba(234,179,8,0.15); border: 1px solid rgba(234,179,8,0.3);">
                  <div class="w-2 h-2 rounded-full bg-wgc-gold-500"></div>
                </div>
                <span class="text-sm font-semibold" style="color: #94a3b8;">{{ item }}</span>
              </div>
            }
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- ==================== PROOF BAND ==================== -->
<div class="bg-wgc-navy-900 border-b border-wgc-navy-800 py-8 text-center px-4 overflow-hidden relative">
  <div class="max-w-4xl mx-auto flex flex-wrap justify-center gap-6 sm:gap-12 text-wgc-white font-bold uppercase tracking-widest text-[11px] mb-2">
    <div class="flex items-center gap-2"><div class="w-1.5 h-1.5 rounded-full bg-wgc-gold-500"></div> Built for Church CRMs</div>
    <div class="flex items-center gap-2"><div class="w-1.5 h-1.5 rounded-full bg-wgc-gold-500"></div> Recurring Giving Engine</div>
    <div class="flex items-center gap-2"><div class="w-1.5 h-1.5 rounded-full bg-wgc-gold-500"></div> ACH + Card Payments</div>
    <div class="flex items-center gap-2"><div class="w-1.5 h-1.5 rounded-full bg-wgc-gold-500"></div> White-label Experience</div>
  </div>
</div>

<!-- ==================== PLATFORMS ==================== -->
<section class="py-24 bg-wgc-off border-b border-wgc-navy-100/30">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-16" appScrollFade>
      <div class="inline-flex items-center px-4 py-1.5 rounded-full bg-wgc-navy-50 text-wgc-navy-600 text-[10px] font-bold tracking-[0.2em] uppercase mb-6 border border-wgc-navy-100">Partnership focus</div>
      <h2 class="text-4xl font-black text-wgc-navy-900 tracking-tight">Built for the platforms you trust</h2>
      <p class="text-lg text-wgc-navy-500 font-medium max-w-2xl mx-auto mt-4">Providing institutional-grade payment rails beneath the software that ministries use every day.</p>
    </div>
    
    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
      @for (platform of ['Church Management (ChMS)', 'Donation Platforms', 'Nonprofit CRMs', 'Faith-based SaaS']; track platform; let i = $index) {
        <div class="p-8 rounded-2xl bg-wgc-white border border-wgc-navy-100 shadow-sm hover:shadow-md transition-all group hover:-translate-y-1" appScrollFade [delay]="i * 100">
           <div class="text-lg font-black text-wgc-navy-900 group-hover:text-wgc-gold-600 transition-colors">{{ platform }}</div>
           <div class="w-8 h-1 bg-wgc-gold-500 mt-4 rounded-full opacity-0 group-hover:opacity-100 transition-opacity"></div>
        </div>
      }
    </div>
  </div>
</section>

<!-- ==================== PARTNER FLOW ==================== -->
<section class="py-24 bg-wgc-white border-b border-wgc-navy-100/30">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
    <h2 class="text-3xl font-black text-wgc-navy-900 sm:text-4xl tracking-tight mb-16">The Partner Flow</h2>
    
    <div class="flex flex-col md:flex-row items-center justify-center md:items-stretch gap-6">
      <div class="w-full md:flex-1 p-10 rounded-3xl border border-wgc-navy-100 bg-wgc-off shadow-sm">
        <div class="text-[10px] font-black text-wgc-navy-400 uppercase tracking-widest mb-4">Your Application</div>
        <div class="text-2xl font-black text-wgc-navy-900 tracking-tight">Partner Software</div>
      </div>
      
      <div class="flex items-center justify-center px-4">
        <lucide-icon [img]="ArrowRight" class="w-8 h-8 text-wgc-gold-500 hidden md:block"></lucide-icon>
        <lucide-icon [img]="ChevronDown" class="w-8 h-8 text-wgc-gold-500 md:hidden"></lucide-icon>
      </div>
      
      <div class="w-full md:flex-1 p-10 rounded-3xl border border-wgc-gold-200 bg-wgc-navy-900 shadow-2xl relative overflow-hidden">
        <div class="absolute inset-0 opacity-10 pointer-events-none select-none" style="font-size: 8rem; color: #eab308; font-weight: 900;">✝</div>
        <div class="relative z-10 text-[10px] font-black text-wgc-gold-500 uppercase tracking-widest mb-4">Infrastructure</div>
        <div class="relative z-10 text-2xl font-black text-white tracking-tight">WGC Payments API</div>
      </div>
      
      <div class="flex items-center justify-center px-4">
        <lucide-icon [img]="ArrowRight" class="w-8 h-8 text-wgc-gold-500 hidden md:block"></lucide-icon>
        <lucide-icon [img]="ChevronDown" class="w-8 h-8 text-wgc-gold-500 md:hidden"></lucide-icon>
      </div>
      
      <div class="w-full md:flex-1 p-10 rounded-3xl border border-wgc-navy-100 bg-wgc-off shadow-sm">
        <div class="text-[10px] font-black text-wgc-navy-400 uppercase tracking-widest mb-4">Final Recipients</div>
        <div class="text-2xl font-black text-wgc-navy-900 tracking-tight">Ministry Merchants</div>
      </div>
    </div>
  </div>
</section>

<!-- ==================== ADVANTAGE ==================== -->
<section class="py-24 lg:py-32 bg-wgc-off border-t border-wgc-navy-100/10">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-20" appScrollFade>
      <h2 class="text-4xl font-black text-wgc-navy-900 mb-6 tracking-tight">The Partner Advantage</h2>
      <p class="mt-4 max-w-2xl text-lg text-wgc-navy-500 font-medium mx-auto">Everything you need to launch a world-class payment platform, without the burden.</p>
    </div>
    
    <div class="grid md:grid-cols-2 lg:grid-cols-3 gap-10">
      @for (feature of features; track feature.title; let i = $index) {
        <div class="bg-wgc-white p-10 rounded-3xl border border-wgc-navy-100 shadow-sm hover:shadow-lg transition-all transform hover:-translate-y-1" appScrollFade [delay]="i * 80">
          <div class="w-12 h-12 bg-wgc-navy-50 rounded-2xl flex items-center justify-center text-wgc-gold-500 mb-8 border border-wgc-navy-100">
            <lucide-icon [img]="feature.icon" class="w-6 h-6"></lucide-icon>
          </div>
          <h3 class="text-xl font-black text-wgc-navy-900 mb-4 tracking-tight">{{ feature.title }}</h3>
          <p class="text-wgc-navy-500 font-medium leading-relaxed">{{ feature.description }}</p>
        </div>
      }
    </div>
  </div>
</section>

<!-- ==================== QUOTE ==================== -->
<section class="py-24 bg-wgc-white border-y border-wgc-navy-50">
  <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center" appScrollFade>
    <div class="w-12 h-1.5 metallic-gold mx-auto mb-10 rounded-full"></div>
    <h2 class="text-4xl font-black text-wgc-navy-900 mb-10 tracking-tight leading-tight">Embedded Payments for Church and Nonprofit Software</h2>
    <div class="prose prose-lg mx-auto text-wgc-navy-500 space-y-8">
      <p class="text-2xl italic font-black text-wgc-navy-900 leading-snug">
        "We exist to make software companies that serve churches more successful. We're not building a direct-to-church product. We're your silent infrastructure."
      </p>
      <p class="text-lg font-medium leading-relaxed">
        WGC is the institutional infrastructure under your software — aligned with your growth and your mission. By using a transferable vault and providing flat-rate ACH, we ensure that your platform scales efficiently while honoring the donors' generosity.
      </p>
    </div>
  </div>
</section>

<!-- ==================== DEV PREVIEW ==================== -->
<section class="py-24 lg:py-32 bg-wgc-white relative overflow-hidden">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
    <div class="lg:grid lg:grid-cols-2 lg:gap-24 items-center">
      <div appScrollFade>
        <div class="inline-flex items-center px-4 py-1.5 rounded-full bg-wgc-navy-50 text-wgc-navy-600 text-[10px] font-bold tracking-[0.25em] uppercase mb-8 border border-wgc-navy-100">Developer First</div>
        <h2 class="text-4xl font-black text-wgc-navy-900 sm:text-5xl mb-8 tracking-tight">Integrate in days, not quarters</h2>
        <p class="text-lg text-wgc-navy-500 mb-10 leading-relaxed font-medium">
          WGC provides a strictly typed REST API that your team will love. Process donations, manage merchants, and handle webhooks with a clean, modern SDK.
        </p>
        <a routerLink="/developers" class="metallic-gold inline-flex items-center justify-center px-10 py-4 text-sm font-black rounded-full text-wgc-navy-900 shadow-xl transition-all hover:scale-105 uppercase tracking-widest">
          View API Docs
        </a>
      </div>
      
      <div class="mt-16 lg:mt-0" appScrollFade [delay]="200">
        <div class="rounded-[2.5rem] overflow-hidden shadow-2xl bg-wgc-navy-900 border border-wgc-navy-800 shadow-wgc-gold-500/10">
          <div class="px-8 py-5 flex items-center bg-wgc-white/[0.03] border-b border-white/10">
            <div class="flex space-x-2">
              <div class="w-2.5 h-2.5 rounded-full bg-red-400"></div>
              <div class="w-2.5 h-2.5 rounded-full bg-wgc-gold-400"></div>
              <div class="w-2.5 h-2.5 rounded-full bg-green-400"></div>
            </div>
            <span class="mx-auto text-[10px] font-black text-wgc-navy-400 uppercase tracking-widest">donation_request.ts</span>
          </div>
          <div class="p-10 font-mono text-[13px] leading-relaxed">
            <pre><code style="color: #94a3b8;"><span style="color: #eab308;">const</span> donation = <span style="color: #eab308;">await</span> wgc.<span style="color: #cbd5e1;">payments</span>.<span style="color: #cbd5e1;">create</span>(&#123;
  merchantId: <span style="color: #eab308;">'ch_fbc_01'</span>,
  amount: <span style="color: #f8fafc;">5000</span>,
  fund: <span style="color: #eab308;">'general'</span>,
  donor: &#123; email: <span style="color: #eab308;">'user&#64;kingdom.org'</span> &#125;
&#125;);</code></pre>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- ==================== COMPARISON ==================== -->
<section class="py-24 bg-wgc-off">
  <div class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="text-center mb-16" appScrollFade>
      <h2 class="text-3xl font-black text-wgc-navy-900 tracking-tight mb-4">Purpose-Built Infrastructure</h2>
      <p class="text-lg text-wgc-navy-500 font-medium max-w-2xl mx-auto">Why software platforms choose WGC over generic payment rails.</p>
    </div>
    
    <div class="overflow-hidden rounded-3xl bg-wgc-white shadow-xl border border-wgc-navy-100" appScrollFade>
      <table class="w-full text-left">
        <thead class="bg-wgc-navy-900 text-white">
          <tr>
            <th class="py-6 px-10 text-[10px] font-black uppercase tracking-widest">Platform Feature</th>
            <th class="py-6 px-10 text-[10px] font-black uppercase tracking-widest text-center text-wgc-gold-500">WGC Payments</th>
            <th class="py-6 px-10 text-[10px] font-black uppercase tracking-widest text-center opacity-50">Horizontal Rails</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-wgc-navy-50">
          @for (row of [
            { f: 'Built for Ministries', w: 'Native alignment', s: 'Broad Retail' },
            { f: 'ACH Optimization', w: '25¢ Flat-rate', s: 'Margin heavy' },
            { f: 'Experience', w: 'Fully White-labeled', s: 'Redirected' }
          ]; track row.f) {
            <tr>
              <td class="py-6 px-10 font-black text-wgc-navy-900">{{ row.f }}</td>
              <td class="py-6 px-10 text-center font-bold text-wgc-navy-700 bg-wgc-gold-500/5">{{ row.w }}</td>
              <td class="py-6 px-10 text-center text-wgc-navy-400">{{ row.s }}</td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  </div>
</section>

<!-- ==================== CTA ==================== -->
<app-cta-section
  headline="Ready to power Kingdom giving?"
  subheadline="Contact our team to review your software roadmap and request sandbox access."
  ctaText="Contact us"
  ctaLink="/contact"
></app-cta-section>
