// WGC_Frontend/src/app/pages/register/register.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { FormsModule, ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { ArrowLeft, LucideAngularModule } from 'lucide-angular';


@Component({
  selector: 'app-register',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, ReactiveFormsModule, LucideAngularModule],
  template: `
    <div class="min-h-screen bg-wgc-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
      <div class="sm:mx-auto sm:w-full sm:max-w-md text-center">
        <a routerLink="/" class="inline-flex items-center mb-10 cursor-pointer group">
          <!-- New Primary WGC Logo Asset -->
          <div class="h-14 w-auto transform transition-all duration-300">
            <img src="/wgc-brand-final.png" alt="WGC Payments" class="h-full w-auto object-contain">
          </div>
        </a>
        <a routerLink="/" class="inline-flex items-center mb-6 text-xs font-bold text-wgc-navy-400 hover:text-wgc-navy-900 transition-all uppercase tracking-widest group">
          <lucide-icon [img]="ArrowLeft" class="w-3 h-3 mr-2 group-hover:-translate-x-1 transition-transform"></lucide-icon>
          Back to Home
        </a>
        <h2 class="text-3xl font-extrabold text-wgc-navy-900 tracking-tight">Create your account</h2>
        <p class="mt-3 text-sm text-wgc-navy-400 font-medium">
          Or
          <a routerLink="/login" class="text-wgc-gold-600 hover:text-wgc-gold-500 font-bold transition-colors">sign in to existing account</a>
        </p>
      </div>

      <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md px-4">
        <div class="bg-wgc-white py-8 px-6 shadow-xl border border-wgc-gray-100 rounded-xl sm:px-10">
          <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="space-y-6">
            <div>
              <label for="email" class="block text-xs font-bold text-wgc-navy-400 uppercase tracking-widest mb-2">Email address</label>
              <div class="mt-1">
                <input id="email" type="email" formControlName="email" autocomplete="email" required
                  placeholder="name&#64;church.org"
                  class="appearance-none block w-full px-4 py-3 border border-wgc-navy-100 rounded-xl shadow-sm placeholder-wgc-navy-200 focus:outline-none focus:ring-2 focus:ring-wgc-gold-500/20 focus:border-wgc-gold-500 sm:text-sm bg-wgc-off/50">
              </div>
              <div *ngIf="registerForm.get('email')?.touched && registerForm.get('email')?.errors" class="mt-1 text-xs text-red-600">
                <span *ngIf="registerForm.get('email')?.errors?.['email']">Please enter a valid email address.</span>
                <span *ngIf="registerForm.get('email')?.errors?.['required']">Email is required.</span>
              </div>
            </div>

            <div>
              <label for="password" class="block text-xs font-bold text-wgc-navy-400 uppercase tracking-widest mb-2">Password</label>
              <div class="mt-1">
                <input id="password" type="password" formControlName="password" autocomplete="new-password" required
                  placeholder="••••••••"
                  class="appearance-none block w-full px-4 py-3 border border-wgc-navy-100 rounded-xl shadow-sm placeholder-wgc-navy-200 focus:outline-none focus:ring-2 focus:ring-wgc-gold-500/20 focus:border-wgc-gold-500 sm:text-sm bg-wgc-off/50">
              </div>
              <div *ngIf="registerForm.get('password')?.touched && registerForm.get('password')?.errors" class="mt-1 text-xs text-red-600">
                <span *ngIf="registerForm.get('password')?.errors?.['minlength']">Password must be at least 8 characters.</span>
              </div>
            </div>

            <div>
              <label for="role" class="block text-sm font-medium text-wgc-gray-700">I am a...</label>
              <div class="mt-1">
                <select id="role" formControlName="role" 
                  class="block w-full px-3 py-2 border border-wgc-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-wgc-blue-500 focus:border-wgc-blue-500 sm:text-sm">
                  <option value="partner_admin">Software Partner</option>
                  <option value="church_admin">Church Administrator</option>
                </select>
              </div>
            </div>

            <div class="flex items-center">
              <input id="terms" name="terms" type="checkbox" required
                class="h-4 w-4 text-wgc-blue-600 focus:ring-wgc-blue-500 border-wgc-gray-300 rounded">
              <label for="terms" class="ml-2 block text-sm text-wgc-gray-900">
                I agree to the <a href="#" class="text-wgc-blue-600">Terms</a> and <a href="#" class="text-wgc-blue-600">Privacy Policy</a>
              </label>
            </div>

            <div *ngIf="errorMessage()" class="p-3 rounded-md bg-red-50 text-sm text-red-600 border border-red-100">
              {{ errorMessage() }}
            </div>

            <div>
              <button type="submit" [disabled]="registerForm.invalid || isLoading()"
                class="w-full flex justify-center py-3 px-4 metallic-gold rounded-xl shadow-lg text-sm font-bold transition-all transform hover:scale-[1.02] active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none">
                <span *ngIf="!isLoading()">Create account</span>
                <span *ngIf="isLoading()" class="flex items-center gap-2">
                  <svg class="animate-spin h-4 w-4 text-wgc-navy-900" viewBox="0 0 24 24">
                    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" fill="none"></circle>
                    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Creating account...
                </span>
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `
})
export class RegisterComponent {
  readonly ArrowLeft = ArrowLeft;
  private fb = inject(FormBuilder);
  private authService = inject(AuthService);
  private router = inject(Router);

  isLoading = signal(false);
  errorMessage = signal<string | null>(null);

  registerForm = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(8)]],
    role: ['partner_admin', Validators.required]
  });

  onSubmit() {
    if (this.registerForm.valid) {
      this.isLoading.set(true);
      this.errorMessage.set(null);
      
      this.authService.register(this.registerForm.value).subscribe({
        next: () => {
          this.router.navigate(['/login'], { queryParams: { registered: 'true' } });
        },
        error: (err) => {
          this.isLoading.set(false);
          this.errorMessage.set(err.error?.message || 'Failed to create account. Please try again.');
        }
      });
    }
  }
}

// wgc-next/src/app/auth/register/page.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Loader2, ShieldCheck } from "lucide-react";
import { cn } from "@/lib/utils";

const registerSchema = z.object({
  fullName: z.string().min(2, "Full name must be at least 2 characters."),
  email: z.string().email("Please enter a valid email address."),
  password: z.string().min(8, "Password must be at least 8 characters."),
  organizationName: z.string().min(2, "Organization name must be at least 2 characters."),
});

type RegisterFormValues = z.infer<typeof registerSchema>;

export default function RegisterPage() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<RegisterFormValues>({
    resolver: zodResolver(registerSchema),
  });

  const onSubmit = async (data: RegisterFormValues) => {
    setIsLoading(true);
    setErrorMessage(null);

    try {
      const response = await fetch("/api/auth/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(data),
      });

      const result = await response.json();

      if (!response.ok) {
        throw new Error(result.message || "Failed to create account");
      }

      // Store in localStorage
      localStorage.setItem("wgc_auth_token", result.token);
      localStorage.setItem("wgc_user_data", JSON.stringify(result.user));

      // Redirect to onboarding application
      router.push("/dashboard/church/onboarding");
    } catch (err: any) {
      setErrorMessage(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8 font-sans">
      <div className="sm:mx-auto sm:w-full sm:max-w-md text-center">
        <Link href="/" className="inline-block mb-8">
           <div className="flex items-center gap-2">
             <div className="w-10 h-10 rounded-xl bg-wgc-gold-500 flex items-center justify-center shadow-lg shadow-wgc-gold-500/20 transform rotate-12">
               <span className="text-wgc-navy-900 font-black text-xl -rotate-12">W</span>
             </div>
             <span className="font-black text-wgc-navy-900 uppercase tracking-tighter text-2xl">WGC Payments</span>
           </div>
        </Link>
        <h2 className="text-3xl font-bold text-wgc-navy-900 tracking-tight">Create your onboarding account</h2>
        <p className="mt-3 text-sm text-slate-500 font-medium">
          Start your mission-driven sub-merchant application.
        </p>
      </div>

      <div className="mt-8 sm:mx-auto sm:w-full sm:max-w-md px-4">
        <div className="bg-white py-10 px-8 shadow-[0_32px_64px_-16px_rgba(0,0,0,0.1)] border border-slate-200 rounded-[2.5rem] sm:px-12">
          <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
            <div className="grid grid-cols-1 gap-6">
              <div>
                <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mb-2 font-mono">Full Name</label>
                <input
                  {...register("fullName")}
                  className={cn(
                    "block w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-wgc-gold-500/20 focus:border-wgc-gold-500 transition-all font-medium",
                    errors.fullName && "border-red-300"
                  )}
                  placeholder="John Doe"
                />
                {errors.fullName && <p className="mt-1 text-xs text-red-500">{errors.fullName.message}</p>}
              </div>

              <div>
                <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mb-2 font-mono">Organization Name</label>
                <input
                  {...register("organizationName")}
                  className={cn(
                    "block w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-wgc-gold-500/20 focus:border-wgc-gold-500 transition-all font-medium",
                    errors.organizationName && "border-red-300"
                  )}
                  placeholder="Grace Community Church"
                />
                {errors.organizationName && <p className="mt-1 text-xs text-red-500">{errors.organizationName.message}</p>}
              </div>

              <div>
                <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mb-2 font-mono">Email Address</label>
                <input
                  type="email"
                  {...register("email")}
                  className={cn(
                    "block w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-wgc-gold-500/20 focus:border-wgc-gold-500 transition-all font-medium",
                    errors.email && "border-red-300"
                  )}
                  placeholder="admin@church.org"
                />
                {errors.email && <p className="mt-1 text-xs text-red-500">{errors.email.message}</p>}
              </div>

              <div>
                <label className="block text-[10px] font-bold text-slate-400 uppercase tracking-[0.2em] mb-2 font-mono">Password</label>
                <input
                  type="password"
                  {...register("password")}
                  className={cn(
                    "block w-full px-4 py-3 bg-slate-50 border border-slate-100 rounded-2xl text-sm focus:outline-none focus:ring-2 focus:ring-wgc-gold-500/20 focus:border-wgc-gold-500 transition-all font-medium",
                    errors.password && "border-red-300"
                  )}
                  placeholder="••••••••"
                />
                {errors.password && <p className="mt-1 text-xs text-red-500">{errors.password.message}</p>}
              </div>
            </div>

            {errorMessage && (
              <div className="p-4 bg-red-50 border border-red-100 rounded-2xl text-xs font-bold text-red-600 uppercase tracking-widest font-mono">
                {errorMessage}
              </div>
            )}

            <button
              type="submit"
              disabled={isLoading}
              className="w-full py-4 bg-wgc-navy-900 text-white rounded-2xl text-[11px] font-bold uppercase tracking-[0.3em] shadow-xl hover:bg-black transition-all transform active:scale-95 disabled:opacity-50 flex items-center justify-center font-mono"
            >
              {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : "Initiate Onboarding"}
            </button>

            <div className="flex items-center justify-center gap-2 pt-4 border-t border-slate-50">
              <ShieldCheck className="w-4 h-4 text-wgc-gold-500" />
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest font-mono">Bank-grade security protocol</span>
            </div>
          </form>

          <p className="mt-8 text-center text-xs font-bold text-slate-400 uppercase tracking-[0.1em] font-mono">
            Already have an account?{" "}
            <Link href="/auth/login" className="text-wgc-gold-600 hover:text-black transition-colors">
              Sign In
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}
