// WGC_Frontend/src/components/layout/Header.tsx
"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Menu, X } from "lucide-react";
import { cn } from "@/lib/utils";
import GatewayIcon from "@/components/ui/GatewayIcon";

const NAV_LINKS = [
  { name: "Home", href: "/" },
  { name: "Partners", href: "/software-partners" },
  { name: "Pricing", href: "/pricing" },
  { name: "Developers", href: "/developers" },
  { name: "Demo", href: "/demo/donation" },
];

export default function Header() {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const pathname = usePathname();

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 10);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  const closeMenu = () => setIsMobileMenuOpen(false);

  return (
    <header
      className={cn(
        "sticky top-0 z-50 w-full transition-all duration-300 border-b",
        scrolled 
          ? "bg-white/80 backdrop-blur-md border-wgc-navy-100 shadow-sm py-2" 
          : "bg-white border-transparent py-4 md:py-6"
      )}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-4 lg:px-0">
        <div className="flex justify-between items-center">
          {/* Logo */}
          <Link href="/" onClick={closeMenu} className="flex items-center gap-3 group">
            <GatewayIcon className="h-12 md:h-16 w-auto transition-transform group-hover:scale-105 duration-500" />
              <div className="flex flex-col">
                <div className="flex items-baseline">
                  <span className="text-3xl md:text-5xl font-bold tracking-[0.05em] text-[#010409] leading-[0.9]">WGC</span>
                </div>
                <div className="flex flex-col">
                  <span className="text-[7px] md:text-[9px] uppercase tracking-[0.25em] text-[#010409]/70 whitespace-nowrap leading-tight mt-1">Waypoint Gateway Collective</span>
                  <div className="h-[1.5px] w-full bg-[#eab308] my-1"></div>
                  <span className="text-[6px] md:text-[8px] italic text-[#010409]/50 leading-none">1 Samuel 7:12</span>
                </div>
              </div>
          </Link>

          {/* Right Align: Navigation + CTA */}
          <div className="hidden lg:flex items-center gap-12">
            <nav className="flex items-center gap-10">
              {NAV_LINKS.map((link) => (
                <Link 
                  key={link.href}
                  href={link.href}
                  className={cn(
                    "text-[12px] tracking-[0.1em] font-bold transition-all hover:text-black",
                    pathname === link.href 
                      ? "text-[#eab308]" 
                      : "text-[#010409]"
                  )}
                >
                  {link.name}
                </Link>
              ))}
            </nav>

            {/* Desktop CTA */}
            <div className="flex items-center gap-6">
              <Link href="/login" className="text-[12px] font-bold text-[#010409] hover:text-[#eab308] transition-all tracking-[0.1em]">
                Login
              </Link>
              <Link 
                href="/register" 
                className="metallic-gold px-10 py-4 text-[13px] font-bold rounded-2xl shadow-2xl transition-all tracking-wide"
              >
                Get Started
              </Link>
            </div>
          </div>

          {/* Mobile menu button */}
          <div className="flex items-center md:hidden">
            <button 
              type="button" 
              onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
              className="inline-flex items-center justify-center p-2 rounded-xl text-white hover:bg-wgc-navy-900 transition-all"
            >
              <span className="sr-only">Open main menu</span>
              {isMobileMenuOpen ? <X className="h-6 w-6" /> : <Menu className="h-6 w-6" />}
            </button>
          </div>
        </div>
      </div>

      {/* Mobile menu */}
      <div className={cn(
        "lg:hidden absolute top-full left-0 w-full transition-all duration-300 ease-in-out bg-wgc-navy-950 shadow-2xl border-t border-white/5 overflow-hidden",
        isMobileMenuOpen ? "max-h-screen opacity-100" : "max-h-0 opacity-0 pointer-events-none"
      )}>
        <div className="px-8 pt-8 pb-12 space-y-4">
          <div className="mb-6">
            <span className="text-[10px] font-bold text-[#C9973A] uppercase tracking-[0.4em] block mb-6">Platform</span>
            <div className="flex flex-col gap-4">
              {NAV_LINKS.map((link) => (
                <Link
                  key={link.href}
                  href={link.href}
                  onClick={closeMenu}
                  className={cn(
                    "text-xl font-bold tracking-tight transition-all",
                    pathname === link.href 
                      ? "text-[#eab308]" 
                      : "text-white hover:text-[#eab308]"
                  )}
                >
                  {link.name === "Pricing" ? "Fee Structure" : 
                   link.name === "Home" ? "Home" :
                   link.name === "Partners" ? "Partners" :
                   link.name === "Developers" ? "Api Reference" :
                   link.name}
                </Link>
              ))}
            </div>
          </div>
          
          <div className="mt-8 pt-8 border-t border-white/5 flex flex-col gap-4">
            <Link 
              href="/login" 
              onClick={closeMenu}
              className="w-full flex items-center justify-center px-6 py-4 border border-white/10 rounded-xl text-[12px] font-bold text-white bg-white/5 tracking-wide transition-all active:scale-95"
            >
              Institutional Login
            </Link>
            <Link 
              href="/register" 
              onClick={closeMenu}
              className="w-full flex items-center justify-center px-6 py-4 metallic-gold rounded-xl text-[12px] font-bold text-wgc-navy-950 shadow-lg tracking-wide transition-all active:scale-95"
            >
              Request Connection
            </Link>
          </div>
        </div>
      </div>
    </header>
  );
}

// WGC_Frontend_LEGACY/src/app/components/header/header.component.ts
import { Component, signal, inject } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Menu, X, ArrowRight, MapPin } from 'lucide-angular';
import { AuthService } from '../../services/auth.service';
import { ScrollFadeDirective } from '../../directives/scroll-fade.directive';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [RouterLink, RouterLinkActive, CommonModule, LucideAngularModule, ScrollFadeDirective],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent {
  authService = inject(AuthService);
  readonly Menu = Menu;
  readonly X = X;
  readonly ArrowRight = ArrowRight;
  readonly MapPin = MapPin;
  
  isMobileMenuOpen = signal(false);

  toggleMenu() {
    this.isMobileMenuOpen.update(v => !v);
  }

  closeMenu() {
    this.isMobileMenuOpen.set(false);
  }
}

<header
  class="sticky top-0 z-50 w-full bg-white border-b border-wgc-navy-50 shadow-sm transition-all duration-300">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center py-4 md:py-6">

      <!-- Logo -->
      <a routerLink="/" (click)="closeMenu()" class="block flex-shrink-0 group">
        <img src="/wgc-logo.svg" alt="Waypoint Gateway Collective"
          class="h-[60px] md:h-[75px] w-auto transition-transform group-hover:scale-105 duration-500">
      </a>

      <!-- Right Align: Navigation + CTA -->
      <div class="hidden md:flex items-center gap-10">
        <!-- Desktop Navigation -->
        <nav class="flex items-center space-x-8">
          <a routerLink="/" routerLinkActive="text-wgc-gold-600 font-black"
            [routerLinkActiveOptions]="{exact: true}"
            class="text-[12px] uppercase tracking-[0.2em] font-black text-wgc-navy-950 hover:text-black transition-all">Home</a>
          <a routerLink="/software-partners" routerLinkActive="text-wgc-gold-600 font-black"
            class="text-[12px] uppercase tracking-[0.2em] font-black text-wgc-navy-950 hover:text-black transition-all">Partners</a>
          <a routerLink="/pricing" routerLinkActive="text-wgc-gold-600 font-black"
            class="text-[12px] uppercase tracking-[0.2em] font-black text-wgc-navy-950 hover:text-black transition-all">Pricing</a>
          <a routerLink="/developers" routerLinkActive="text-wgc-gold-600 font-black"
            class="text-[12px] uppercase tracking-[0.2em] font-black text-wgc-navy-950 hover:text-black transition-all">Developers</a>
          <a routerLink="/demo/donation" routerLinkActive="text-wgc-gold-600 font-black"
            class="text-[12px] uppercase tracking-[0.2em] font-black text-wgc-navy-950 hover:text-black transition-all">Demo</a>
        </nav>

        <!-- Desktop CTA -->
        <div class="flex items-center gap-6">
        <ng-container *ngIf="!(authService.currentUser$ | async); else authButtons">
          <a routerLink="/login"
            class="text-[11px] font-black text-wgc-navy-950 hover:text-black transition-all uppercase tracking-[0.2em]">
            Login
          </a>
          <a routerLink="/register"
            class="bg-wgc-gold-500 text-wgc-navy-950 px-8 py-3.5 rounded-2xl text-[11px] font-black shadow-lg shadow-wgc-gold-500/20 hover:bg-black hover:text-white hover:scale-105 active:scale-95 transition-all uppercase tracking-widest">
            Get Started
          </a>
        </ng-container>
        <ng-template #authButtons>
          <a routerLink="/dashboard"
            class="bg-wgc-navy-950 text-white px-8 py-3.5 rounded-2xl text-[11px] font-black shadow-xl hover:bg-black hover:scale-105 active:scale-95 transition-all uppercase tracking-widest">
            Go to Console
          </a>
        </ng-template>
        </div>
      </div>

      <!-- Mobile menu button -->
      <div class="flex items-center md:hidden">
        <button type="button" (click)="toggleMenu()"
          class="inline-flex items-center justify-center p-2 rounded-xl text-wgc-navy-950 hover:bg-wgc-off transition-all">
          <span class="sr-only">Open main menu</span>
          <lucide-icon *ngIf="!isMobileMenuOpen()" [img]="Menu" class="block h-6 w-6"></lucide-icon>
          <lucide-icon *ngIf="isMobileMenuOpen()" [img]="X" class="block h-6 w-6"></lucide-icon>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu -->
  <div class="md:hidden" [ngClass]="{'block': isMobileMenuOpen(), 'hidden': !isMobileMenuOpen()}">
    <div class="px-4 pt-4 pb-12 space-y-2 bg-white shadow-2xl border-t border-wgc-navy-50">
      <a routerLink="/" routerLinkActive="bg-wgc-gold-50 text-wgc-gold-600"
        [routerLinkActiveOptions]="{exact: true}" (click)="closeMenu()"
        class="text-wgc-navy-950 hover:bg-wgc-off block px-6 py-4 rounded-2xl text-[10px] font-black uppercase tracking-[0.3em] transition-all">Home</a>
      <a routerLink="/software-partners" routerLinkActive="bg-wgc-gold-50 text-wgc-gold-600"
        (click)="closeMenu()"
        class="text-wgc-navy-950 hover:bg-wgc-off block px-6 py-4 rounded-2xl text-[10px] font-black uppercase tracking-[0.3em] transition-all">Partners</a>
      <a routerLink="/pricing" routerLinkActive="bg-wgc-gold-50 text-wgc-gold-600" (click)="closeMenu()"
        class="text-wgc-navy-950 hover:bg-wgc-off block px-6 py-4 rounded-2xl text-[10px] font-black uppercase tracking-[0.3em] transition-all">Pricing</a>
      <a routerLink="/developers" routerLinkActive="bg-wgc-gold-50 text-wgc-gold-600" (click)="closeMenu()"
        class="text-wgc-navy-950 hover:bg-wgc-off block px-6 py-4 rounded-2xl text-[10px] font-black uppercase tracking-[0.3em] transition-all">Developers</a>
      <a routerLink="/demo/donation" routerLinkActive="bg-wgc-gold-50 text-wgc-gold-600" (click)="closeMenu()"
        class="text-wgc-navy-950 hover:bg-wgc-off block px-6 py-4 rounded-2xl text-[10px] font-black uppercase tracking-[0.3em] transition-all">Demo Flow</a>

      <div class="mt-8 pt-8 border-t border-wgc-navy-50">
        <ng-container *ngIf="!(authService.currentUser$ | async); else mobileAuthButtons">
          <a routerLink="/login" (click)="closeMenu()"
            class="w-full mb-4 flex items-center justify-center px-6 py-4 border border-wgc-navy-100 rounded-2xl text-[10px] font-black text-wgc-navy-950 bg-wgc-off uppercase tracking-widest transition-all active:scale-95">
            Institutional Login
          </a>
          <a routerLink="/register" (click)="closeMenu()"
            class="w-full flex items-center justify-center px-6 py-4 bg-wgc-gold-500 rounded-2xl text-[10px] font-black text-wgc-navy-950 shadow-lg shadow-wgc-gold-500/20 uppercase tracking-widest transition-all active:scale-95">
            Partner Registration
          </a>
        </ng-container>
        <ng-template #mobileAuthButtons>
          <a routerLink="/dashboard" (click)="closeMenu()"
            class="w-full flex items-center justify-center px-6 py-4 bg-wgc-navy-950 rounded-2xl text-[10px] font-black text-white shadow-xl uppercase tracking-widest">
            Institutional Console
          </a>
        </ng-template>
      </div>
    </div>
  </div>
</header>
